### ISSUE TITLE
Create Inhabitant table

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#1]
Create a table with the following attributes and traits. 

| Attribute                         | Type    | Constraints  | Access Level |
| -------------------------------  |:---------:|:----------------:|:------------------:|
| inhabitant_id                   | text      |                     | admin            |
| household_id                   | text      |                     | admin            |
| name                               |  text     |                     | admin             |
| encrypted_name             | text      |                     | worker            |
| age                                  | integer |   >=0             | all                  |
| sex                                  | enum   |  male|female |  all                  |

### Prerequisites 

- [x] #4 create household data

### Tasks

- [x] Create migration and model 

- [x] Apply relevant constraints 

- [x] Passes rspec 

- [x] Passes user tests
