### ISSUE TITLE
Add relationships to models

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#12]
### Tasks 

- [x] Districts has_many villages 

- [x] District has_many households

- [x] District counter cache villages

- [x] District counter cache or query inhabitants 

- [x] District counter cache or query children under 8

- [x] District counter cache or query households 

- [x] District counter cache or llins_distributed

- [x] Villages belong_to districts 

- [x] Villages have_many households 

- [x] Households belong_to villages 

- [x] Households have_many inhabitants 

- [x] Query children under 8 in households 

- [x] Inhabitants belong to households 

- [x] inhabitants counter cache for households

- [x] Village Counter cache for households 

- [x] village Has_many people through households 

- [x] Counter cache people in villages

- [x] Query for under 8 in villages

**Comment by olendorf** [comment]
seems counting children under 8 and llins distributed should work fine doing as needed queries for now. may revisit.
