### ISSUE TITLE
Create District Table

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#2]
Create a table for district data with the following attributes.

| Attribute                         | Type    | Constraints     | Access Level |
| -------------------------------  |:---------:|:------------------:|:------------------:|
| name                              | text      |                        | all                    |
| households                    | integer | counter cache | all                    |
| people                            | integer | counter cache | all                    |
| children_under_8           | integer | query              | all                    |
| total_llins                        | integer | counter cache | all                   |
| llins_to_distribute           | integer |  >=0                  | all                   |

### Prerequisites
 **none**

### Tasks

- [x] Create migration and model 

- [x] Apply relevant constraints 

- [x] Passes rspec 

- [x] Passes user tests

**Comment by olendorf** [comment]
Need to add llin stuff here rather than village i think?
