### ISSUE TITLE
Create village table

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#3]
Create household table with the following attributes and traits

| Attribute                         | Type    | Constraints         | Access Level |
| -------------------------------  |:---------:|:---------------------:|:------------------:|
| district_id                       | integer |  belongs_to        | all                  |
| name                             | text       |                           | all                   |
| number_of_households  | integer  | counter_cache | all                   |  
| number_of_people         | integer  | has_many through; counter cache | all                   |  
| children_under_8           | integer  |  query?                         | all                   |

### Pre Requisites

- [x] #2 Create District table

### Tasks

- [x] Create migration and model 

- [x] Apply relevant constraints 

- [x] Passes rspec 

- [x] Passes user tests
