### ISSUE TITLE
Create Household Table

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#4]
Create household table with the following attributes and traits

| Attribute                         | Type    | Constraints  | Access Level |
| -------------------------------  |:---------:|:----------------:|:------------------:|
| household_id                  | text      |                     | all                 |
| GPS_coordinates           | spatial? |                   | worker           |
| what3words                    | text      |                     | worker           |
| village                             | integer |                       | all                   |
| number_of_people        | integer  |                      | all                    |
| children_under_8          | integer  |                       | all                   |
| number_of_LLINs         | integer  |                       |  all                  |
| LLIN_voucher_number | integer  |                       | all                   |
| LLINs_distributed          | integer  |                      | all                   |
| llin_distribution_date     | date      |                      | all                   |

### Pre Requisites

- [x] #3 create village

### Tasks

- [x] Create migration and model 

- [x] Apply relevant constraints 

- [x] Passes rspec 

- [x] Passes user tests
