### ISSUE TITLE
Active Admin For Inhabitants

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#5]
Add an active admin resource for inhabitants

### Tasks 

- [x] Create page 

- [x] Tweak index and filters as needed 

- [x] Tweak view as needed 

- [x] Tweak form as needed 

  - [x] Ensure belongs to household works 

- [x] Ensure access levels are correct refer to #1 

- [x] Pass user tests
