### ISSUE TITLE
Activeadmin resource for households

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#6]
Add an active admin resource for households

### Tasks 

- [x] Create page 

- [x] Tweak index and filters as needed 

- [x] Tweak view as needed 

- [x] Tweak form as needed 

  - [x] Ensure belongs to village works 

  - [x] Ensure has many inhabitants works

- [x] Ensure access levels are correct refer to #4

- [x] Pass user tests
