### ISSUE TITLE
Activeadmin Resource for villages

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#7]
Add an active admin resource for villages

### Tasks 

- [x] Create page 

- [x] Tweak index and filters as needed 

- [x] Tweak view as needed 

- [x] Tweak form as needed 

  - [x] Ensure belongs to district works 

  - [x] Ensure has_many households works 

- [ ] Ensure access levels are correct refer to #3 

- [ ] Pass user tests
