### ISSUE TITLE
ActiveAdmin resource for Districts

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#8]
Add an active admin resource for districts

### Tasks 

- [x] Create page 

- [x] Tweak index and filters as needed 

- [x] Tweak view as needed 

- [x] Tweak form as needed 

  - [x] Ensure has_many villages works 

- [x] Ensure access levels are correct refer to #2 

- [x] Pass user tests
