### ISSUE TITLE
Download of entire data set

### ISSUE THREAD

**Issue by olendorf** [olendorf/malaria_mosquito_data_entry#9]
provide a mechanism for the entire joined data set to be downloaded, while respecting permissions.

### Prerequisites 

- [ ] #1 

- [ ] #2 

- [ ] #3 

- [ ] #4

May not need others we'll see.

# Tasks

- [ ] Generate CSV on joined table (model?)

- [ ] Attribute restrictions observed 

- [ ] Rspec testing where appropriate 

- [ ] User testing
